server: # REST and WS server
  port: 2333
  address: 127.0.0.1
lavalink:
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.0.1"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false
  server:
    password: "youshallnotpass"
    bufferDurationMs: 400 # The duration of the NAS buffer. Higher values fare better against longer GC pauses
    frameBufferDurationMs: 5000 # How many milliseconds of audio to keep buffered
    youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
    playerUpdateInterval: 5 # How frequently to send player updates to clients, in seconds
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/

level:
  root: INFO
  lavalink: INFO

plugins:
  lavasrc:
    sources:
      spotify: $spotify/enable                  # ref:config.yml
    spotify:
      clientId: $spotify/client-id              # ref:config.yml
      clientSecret: $spotify/client-secret      # ref:config.yml
      countryCode: "US"
      playlistLoadLimit: 6
      albumLoadLimit: 6
